### ISSUE TITLE
Love this game!

### ISSUE THREAD

**Issue by mainaedula** [lwbecker/Chord-Builder#4]
I LOVE this game, it is a great idea and accessible for anyone looking to improve their music theory! I think it would be helpful though if the correct chord was played the first time, because someone without music background may not intuitively know the difference between how a major and minor chord sounds. And then every time after that, if there was a way to play the notes you've tried AND the correct chord, you can compare the difference and pinpoint which note you need to fix.

**Comment by kirstenfreeman** [comment]
That's a great idea - we'll look into that for sure! Thanks so much for the feedback!
