### ISSUE TITLE
Evaluation: Awesome work!

### ISSUE THREAD

**Issue by braxhawk** [lwbecker/Chord-Builder#5]
Awesome project!! The game keeps you hooked with trying to fix the chords. The music is awesome, and would be pleasing to all different types of audiences! A few suggestions/mentions: 
- At first, I was lost on exactly how to play the game, but after the first two chords got right into it
- I tried to use VoiceOver, but could not get it to read the instructions. Not sure if it was just me being unfamiliar with VoiceOver or possibly a little bug in the code
- The instructions made the game doable, but possibly look into adding information on the different types of notes, accidentals, etc!

Overall though, I really enjoyed the game and thought it was well made. I could easily see someone who is in some way impaired or even not, that wants to get into music theory using this and having fun!!

**Comment by kirstenfreeman** [comment]
Thanks for your feedback! We will look into making more instructions/information for the game.
